CREATE DATABASE PHOTOGRAPHY
USE PHOTOGRAPHY

CREATE TABLE PHOTOGRAPHY.EMPLEADO 
( ID INT NOT NULL AUTO_INCREMENT ,
 CEDULA VARCHAR(13) NOT NULL , 
 NOMBRE VARCHAR(25) NOT NULL , 
 APELLIDO VARCHAR(50) NOT NULL , 
 TELEFONO INT NOT NULL , 
 SALARIO INT NOT NULL ,
 CARGO VARCHAR(25),
  PRIMARY KEY (ID)) ENGINE = InnoDB;

  CREATE TABLE PHOTOGRAPHY.SERVICIOS 
  ( ID INT NOT NULL AUTO_INCREMENT ,
  ID_PAQUETE INT NOT NULL , 
  ID_EMPLEADO INT NOT NULL , 
  PRECIO INT NOT NULL , 
  PRIMARY KEY (ID)) ENGINE = InnoDB;

  CREATE TABLE PHOTOGRAPHY.CLIENTE 
  ( ID INT NOT NULL , 
  CEDULA VARCHAR(13) NOT NULL , 
  NOMBRE VARCHAR(25) NOT NULL , 
  APELLIDO VARCHAR(25) NOT NULL , 
  TELEFONO VARCHAR(25) NOT NULL , 
  DIRECCION VARCHAR(250) NOT NULL ) ENGINE = InnoDB;

  CREATE TABLE PHOTOGRAPHY.FACTURA 
  ( ID INT NOT NULL , 
  ID_CLIENTE INT NOT NULL , 
  ID_SERVICIO INT NOT NULL ,
   ID_EMPLEADO INT NOT NULL , 
   FECHA VARCHAR(10) NOT NULL ) ENGINE = InnoDB;

   CREATE TABLE PHOTOGRAPHY.PAQUETE 
   ( ID INT NOT NULL AUTO_INCREMENT , 
   NOMBRE VARCHAR(25) NOT NULL , 
   IMPRESAS INT NOT NULL ,
    DIGITALES INT NOT NULL , 
    ENMARCADA VARCHAR(12) NOT NULL , 
    NUM_PERSONAS INT NOT NULL ,
     PRIMARY KEY (ID)) ENGINE = InnoDB;


     // INSERTANDO CLIENTES

     INSERT INTO CLIENTE (ID, CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (1, '1234567890', 'MARIO', 'DE LOS SANTOS', '(809) 000-0000', 'PAJARIO');
     INSERT INTO CLIENTE (ID, CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (2, '001-123-4567', 'ALTAGRACIA', 'SERVERINO', '(829) 000-0000', 'PADREBILLINI');
     INSERT INTO CLIENTE (ID, CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (1, '002-456-7890', 'ARIEL', 'GARCIA', '(849) 000-0000', 'PAJARIO');

    // INSERTANDO EMPLEADOS

    INSERT INTO EMPLEADO (ID, CEDULA, NOMBRE, APELLIDO, TELEFONO, SALARIO, CARGO) 
    VALUES (1, '402-000-1234', 'MARIA', 'GUZMAN', '809321789', '7000', 'DISEINER'), 
            (2, '402-987-1234', 'MISAEL', 'VAZQUEZ', '849243185', '7000', 'TRAMOLLA');

    //INSERTANDO PAQUETES

    INSERT INTO PAQUETE (ID, NOMBRE, IMPRESAS, DIGITALES, ENMARCADA, NUM_PERSONAS) 
    VALUES (1, 'PLAN A', '10', '10', '8X11', '4'), 
    (2, 'PLAN B', '8', '8', '8X11', '3');

    // INSERTANDO SERVICIO 

    INSERT INTO SERVICIOS (ID, ID_PAQUETE, ID_EMPLEADO, PRECIO) 
    VALUES ('1', '1', '3', '2500'), 
            ('2', '2', '2', '2200');

  // CREANDO FACTURA

    INSERT INTO FACTURA (ID, ID_CLIENTE, ID_SERVICIO, ID_EMPLEADO, FECHA) 
    VALUES ('2021001', 3, 1, 1, '03/05/2021'), 
    ('2021002', 2, 2, 3, '03/05/2021');

    